apiVersion: v1
kind: Service
metadata:
  name: nodered
  namespace: nodered-ns
spec:
  ports:
    - name: nodered-http
      port: 1880
      protocol: TCP
      targetPort: 1880
  selector:
    app: nodered
  type: LoadBalancer
